name: Build & Deploy Development
on:
  push:
    branches:
      - develop

jobs:
  build_and_deploy_development:
    name: Build & Deploy
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
        env:
          ci: true
          USE_FIREBASE: true
      - name: Deploy to Firebase
        run: npm run deploy
        env:
          ci: true
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID_DEVELOPMENT }}
